name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t steparrik/pizza-flow-backend:${{ env.IMAGE_TAG }} -t steparrik/pizza-flow-backend:latest .

      - name: Push Docker image
        run: |
          docker push steparrik/pizza-flow-backend:${{ env.IMAGE_TAG }}
          docker push steparrik/pizza-flow-backend:latest

      - name: Print Image Tag
        run: echo "Pushed Docker image with tag: ${{ env.IMAGE_TAG }}"
